disabled = false
languageCode = "it"
languageName = "Italian"
weight = 1
title = "Giada Taribelli"

[params]
displayName = "IT"
isoCode = "it"
rtl = false
dateFormat = "2 January 2006"
description = "Pedagogista specializzata nella progettazione di esperienze educative e formative attraverso i giochi di ruolo."
logo = "img/logo.PNG"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Giada Taribelli"
email = "giada.taribelli@gmail.com"
image = "img/author.PNG"
imageQuality = 50
headline = "Playful Mind Hungry Heart"
bio = ""
links = [
  { email = "mailto:giada.taribelli@gmail.com" },
  { instagram = "https://instagram.com/giadadiruolo" },
  { telegram = "https://t.me/giadadiruolo" },
  { spotify = "https://open.spotify.com/show/1xUd7hMLVjCUcvDDtqyP5q?si=b4e9b6717de24425" },
]
