baseURL = 'https://giadataribelli.netfly.app'
languageCode = 'it-it'
title = 'Giada Taribelli'
theme = ["github.com/adityatelange/hugo-PaperMod"]
resourceDir = "../resources"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true

[params.homeInfoParams]
Title = "Giada Taribelli"
Content = "Pedagogista, podcaster, giocatrice di ruolo e viaggiatrice"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/giadadiruolo"

[params.profileMode]
enabled = false
title = "Giada Taribelli"
subtitle = "Pedagogista, podcaster, giocatrice di ruolo e viaggiatrice"
imageUrl = ""
imageTitle = "Una mia foto"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "Cerca"
  url = "/search"

  [[params.profileMode.buttons]]
  name = "Articoli"
  url = "/archive/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "posts"
name = "articoli"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "search"
name = "ricerca"
url = "/search"
weight = 5

[[menu.main]]
identifier = "podcasts"
name = "podcasts"
url = "https://duedraghialmicrofono.com/"
weight = 30
