baseURL = 'https://giadataribelli.netfly.app'
languageCode = 'it-it'
title = 'Giada Taribelli'
theme = ["github.com/adityatelange/hugo-PaperMod"]
resourceDir = "../resources"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Pedagogista, podcaster, giocatrice di ruolo e viaggiatrice"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-lightest-blue"
recent_posts_number = 100 

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/giadadiruolo"
